# Generated by Django 6.0.6 on 2026-07-03 11:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('peut_gerer_users', models.BooleanField(default=False)),
                ('peut_gerer_apps', models.BooleanField(default=False)),
                ('peut_voir_dashboard_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id_serveur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Serveur',
                'verbose_name_plural': 'Serveurs',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('departement', models.CharField(blank=True, default='', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='apm.role')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id_application', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('critere', models.BooleanField(default=False, help_text='Application critique')),
                ('statut', models.BooleanField(default=True, help_text='Actif / Inactif')),
                ('date_mise_prod', models.DateField(blank=True, null=True)),
                ('date_fin_vie', models.DateField(blank=True, null=True)),
                ('nombre_utilisateurs', models.PositiveIntegerField(default=0)),
                ('direction_metier', models.CharField(blank=True, default='', max_length=150)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fichier', models.CharField(max_length=200)),
                ('type_fichier', models.CharField(blank=True, default='', max_length=50)),
                ('categorie', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('id_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apm.application')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Environnement',
            fields=[
                ('id_environnement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Ex: DEV, RECETTE, PREPROD, PROD', max_length=50)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('adresse_ip', models.CharField(blank=True, default='', max_length=50)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('cpu', models.CharField(blank=True, default='', max_length=50)),
                ('ram', models.CharField(blank=True, default='', max_length=50)),
                ('hebergeur', models.CharField(blank=True, default='', max_length=100)),
                ('type_hebergement', models.CharField(blank=True, default='', max_length=100)),
                ('docker', models.BooleanField(default=False)),
                ('kubernetes', models.BooleanField(default=False)),
                ('id_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environnements', to='apm.application')),
                ('id_serveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environnements', to='apm.serveur')),
            ],
            options={
                'verbose_name': 'Environnement',
                'verbose_name_plural': 'Environnements',
            },
        ),
        migrations.CreateModel(
            name='CertificatSSL',
            fields=[
                ('id_certificat_ssl', models.AutoField(primary_key=True, serialize=False)),
                ('domaine', models.CharField(max_length=200)),
                ('fournisseur_ssl', models.CharField(blank=True, default='', max_length=150)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, default='', max_length=50)),
                ('id_environnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_ssl', to='apm.environnement')),
            ],
            options={
                'verbose_name': 'Certificat SSL',
                'verbose_name_plural': 'Certificats SSL',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id_contrat', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contrat', models.CharField(max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cout_annuel', models.FloatField(default=0)),
                ('sla', models.CharField(blank=True, default='', max_length=100)),
                ('statut', models.CharField(blank=True, default='', max_length=50)),
                ('id_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='apm.application')),
                ('id_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='apm.fournisseur')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date_incident', models.DateField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, default='', max_length=100)),
                ('cause_racine', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('statut', models.CharField(blank=True, default='Ouvert', max_length=50)),
                ('id_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='apm.application')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entite_name', models.CharField(blank=True, default='', max_length=100)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, default='')),
                ('id_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apm.incident')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='NomDomaine',
            fields=[
                ('id_nom_domaine', models.AutoField(primary_key=True, serialize=False)),
                ('nom_domaine', models.CharField(max_length=200)),
                ('registrar', models.CharField(blank=True, default='', max_length=150)),
                ('dns', models.CharField(blank=True, default='', max_length=200)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('renouvellement_auto', models.BooleanField(default=False)),
                ('id_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noms_domaine', to='apm.application')),
            ],
            options={
                'verbose_name': 'Nom de domaine',
                'verbose_name_plural': 'Noms de domaine',
            },
        ),
    ]
