# Generated by Django 6.0.7 on 2026-07-10 15:20

from django.db import migrations, models


def convert_critere(apps, schema_editor):
    Application = apps.get_model('apm', 'Application')
    for app in Application.objects.all():
        val = getattr(app, 'critere', None)
        # Handle boolean stored values or truthy indicators
        if val in (True, 'True', 'true', '1', 1):
            app.critere = 'eleve'
        else:
            app.critere = 'normal'
        app.save(update_fields=['critere'])


def revert_critere(apps, schema_editor):
    # Best-effort reverse: mark critere 'eleve' as True, others False
    Application = apps.get_model('apm', 'Application')
    for app in Application.objects.all():
        app.critere = True if getattr(app, 'critere', '') == 'eleve' else False
        app.save(update_fields=['critere'])


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environnement',
            name='exige_ssl',
            field=models.BooleanField(default=False, help_text='Cet environnement exige un certificat SSL'),
        ),
        migrations.AlterField(
            model_name='application',
            name='critere',
            field=models.CharField(choices=[('normal', 'Normal'), ('faible', 'Faible'), ('eleve', 'Élevé')], default='normal', help_text="Niveau de criticité de l'application", max_length=10),
        ),
        migrations.RunPython(convert_critere, revert_critere),
    ]
