# Generated by Django 6.0.7 on 2026-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0002_environnement_exige_ssl_alter_application_critere'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exige_ssl',
            field=models.BooleanField(default=False, help_text="Indique si l'application nécessite un certificat SSL"),
        ),
    ]
