# Generated by Django 6.0.7 on 2026-07-13 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0007_documentfichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='archive',
            field=models.BooleanField(default=False, help_text='Application archivée (masquée des listes actives)'),
        ),
        migrations.AddField(
            model_name='application',
            name='type_app',
            field=models.CharField(choices=[('interne', 'Interne'), ('externe', 'Externe')], default='interne', help_text='Application interne (développée/hébergée en interne) ou externe (fournisseur tiers)', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatssl',
            name='archive',
            field=models.BooleanField(default=False, help_text='Certificat archivé'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='archive',
            field=models.BooleanField(default=False, help_text='Contrat archivé'),
        ),
        migrations.AddField(
            model_name='document',
            name='archive',
            field=models.BooleanField(default=False, help_text='Document archivé'),
        ),
        migrations.AddField(
            model_name='environnement',
            name='archive',
            field=models.BooleanField(default=False, help_text='Environnement archivé'),
        ),
        migrations.AddField(
            model_name='nomdomaine',
            name='archive',
            field=models.BooleanField(default=False, help_text='Nom de domaine archivé'),
        ),
        migrations.AlterField(
            model_name='application',
            name='nom',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message="Utilisez uniquement lettres, chiffres, espaces, '-', '_' ou '.' (1 à 150 caractères).", regex='^[A-Za-zÀ-ÿ0-9][A-Za-zÀ-ÿ0-9 _\\-\\.]{0,149}$')]),
        ),
        migrations.AlterField(
            model_name='environnement',
            name='nom',
            field=models.CharField(help_text='Ex: DEV, RECETTE, PREPROD, PROD', max_length=50, validators=[django.core.validators.RegexValidator(message="Utilisez uniquement lettres, chiffres, espaces, '-' ou '_' (1 à 50 caractères).", regex='^[A-Za-zÀ-ÿ0-9][A-Za-zÀ-ÿ0-9 _\\-]{0,49}$')]),
        ),
    ]
